### ISSUE TITLE
when clicking on configuration tab a "page not found" error is displayed

### ISSUE THREAD

**Issue by royharoush** [dradis/dradisframework#110]
![screenshot from 2015-04-26 14 37 05](https://cloud.githubusercontent.com/assets/8113056/7337039/ed09d8c8-ec21-11e4-9b82-745fc0e519ea.png)

**Comment by etdsoft** [comment]
Hi @royharoush thanks for the report, already fixed and will ship in new release. Workaround:

http://discuss.dradisframework.org/t/cant-enter-configuration/127
