### ISSUE TITLE
Unable to export

### ISSUE THREAD

**Issue by childs999** [dradis/dradisframework#122]
Hi

I'm running dradis package (dradis-3.0.0.rc3-linux-x86.tar.gz) and am unable to export anything via HTML/PDF/CSV

Error I receive:
We're sorry, but something went wrong.
If you are the application owner check the logs for more information

Any assistance would be greatly appreciated.

Cheers,

Sam

**Comment by etdsoft** [comment]
Have you checked this thread?
http://discuss.dradisframework.org/t/export-csv-html-pdf-error/177

**Comment by childs999** [comment]
Hi

That mentions a fix using git - but I am not using the git installed version.
As mentioned I am using the package version (dradis-3.0.0.rc3-linux-x86.tar.gz)

**Comment by childs999** [comment]
Hi

Any other suggestions to assist me?

Thanks

Sam

**Comment by kab00kie** [comment]
I am in the same boat and would like some help.  Anxious to see what the report output looks like from Dradis.

**Comment by etdsoft** [comment]
@kab00kie at the moment the fix is in git, we need to prepare new packages with it, so you can wait or use the git instructions to get up and running
