### ISSUE TITLE
logo_small.png isn't precompiled

### ISSUE THREAD

**Issue by digininja** [dradis/dradisframework#75]
I just installed on a new machine and after doing a reset and allowing it to compile things I've got the following error:

Started GET "/" for 127.0.0.1 at 2012-07-09 12:03:03 +0100
Processing by HomeController#index as HTML
Redirected to https://localhost:3004/wizard
Filter chain halted as :show_first_time_wizard rendered or redirected
Completed 302 Found in 5ms (ActiveRecord: 0.0ms)

Started GET "/wizard" for 127.0.0.1 at 2012-07-09 12:03:04 +0100
Processing by WizardController#index as HTML
  Rendered wizard/index.html.erb within layouts/wizard (100.6ms)
Completed 500 Internal Server Error in 176ms

ActionView::Template::Error (logo_small.png isn't precompiled):
    1: <div class="post">
    2:   <div class="header">&nbsp;</div>
    3:   <div class="content">
    4:     <%= image_tag 'logo_small.png', :class => 'floatleft', :height => 200, :width => 200, :alt => 'Dradis Framework logo' %>
    5: 
    6:       <h2>What is Dradis?</h2>
    7:       <p><strong>Dradis</strong> is an open source framework to enable effective
  app/views/wizard/index.html.erb:4:in `_app_views_wizard_index_html_erb__105888267_86671160'

**Comment by rstarlet** [comment]
Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml` 

help me about this

**Comment by etdsoft** [comment]
@rstarlet since yours is more of usage issue, can you please post it on http://discuss.dradisframework.org?

I'm going to close this issue as it refers to legacy 2.9 version of Dradis.
